turtle_life_node:
  ros__parameters:
    number_of_turtles: 5
    draw_circle: False
    tolerance_distance: 0.01
    max_linear_velocity: 1.0
    min_linear_velocity: 0.1
    max_angular_velocity: 1.0
    min_angular_velocity: 0.1
    use_pid: True
    pid_p: 3.0
    pid_i: 0.4
    pid_d: 1.2
    setpoint: 5.0